# Generated by Django 5.1.1 on 2024-10-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='shop/images')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
